### ISSUE TITLE
Echo not starting at boot

### ISSUE THREAD

**Issue by nico202** [mafik/echo#6]
Hi, thanks for the app.
I'm running android 5.1.1, echo is working, but right now it wont start automatically at boot (it starts only when I run it for the first time, so every time I do a reboot if I forget to open the app again it wont work).
Can someone help?

Thanks

**Comment by no-go** [comment]
I had the same problem. The App must be installed on "internal" and not on "sdcard" to receive the booting intent. There is a AndroidManifest.xml file in the code. Add ...

android:installLocation="internalOnly"

... to the <manifest> Tag. This schould work :-D

**Comment by mafik** [comment]
Thanks!
